"""Auto-generated TypedDict classes from JSON schema.

DO NOT EDIT THIS FILE MANUALLY.
Generated by: python generate_dtos.py

To regenerate, run from the repository root:
    python generate_dtos.py
"""

from __future__ import annotations

from typing import NotRequired, TypedDict


class TimeSpan(TypedDict):
    Start: str
    End: str


class ConfigurationReference(TypedDict):
    ID: str
    TimeStamp: str


class DataSetTabular(TypedDict):
    TimeStamp: str
    Value: list[str]
    Quality: NotRequired[list[str]]


class DataSetEvent(TypedDict):
    TimeStamp: str
    DataChannelID: str
    Value: str
    Quality: NotRequired[str]


class Header(TypedDict):
    ShipID: str
    TimeSpan: NotRequired[TimeSpan]
    DateCreated: NotRequired[str]
    DateModified: NotRequired[str]
    Author: NotRequired[str]
    SystemConfiguration: NotRequired[list[ConfigurationReference]]


class TabularData(TypedDict):
    NumberOfDataSet: NotRequired[int]
    NumberOfDataChannel: NotRequired[int]
    DataChannelID: NotRequired[list[str]]
    DataSet: NotRequired[list[DataSetTabular]]


class EventData(TypedDict):
    NumberOfDataSet: NotRequired[int]
    DataSet: NotRequired[list[DataSetEvent]]


class TimeSeriesData(TypedDict):
    DataConfiguration: NotRequired[ConfigurationReference]
    TabularData: NotRequired[list[TabularData]]
    EventData: NotRequired[EventData]


class Package(TypedDict):
    Header: NotRequired[Header]
    TimeSeriesData: list[TimeSeriesData]


class TimeSeriesDataPackage(TypedDict):
    Package: Package
