#!/usr/bin/env python3
"""Generate Python TypedDict classes from JSON schemas.

This script generates Python DTO types from the JSON schema files
in the schemas/json/ directory using TypedDict for zero-overhead JSON mapping.

Usage:
    python generate_dtos.py

Requirements:
    pip install datamodel-code-generator

The generated files are placed in:
    python/src/vista_sdk/system_text_json/data_channel_list/data_channel_list.py
    python/src/vista_sdk/system_text_json/time_series_data/time_series_data.py
"""

import subprocess
import sys
from pathlib import Path

# Paths relative to this script (script is in python/ folder)
SCRIPT_DIR = Path(__file__).parent
SCHEMA_DIR = SCRIPT_DIR.parent / "schemas" / "json"
OUTPUT_DIR = SCRIPT_DIR / "src" / "vista_sdk" / "system_text_json"

# Schema to output mapping
SCHEMAS = {
    "DataChannelList.schema.json": "data_channel_list/data_channel_list.py",
    "TimeSeriesData.schema.json": "time_series_data/time_series_data.py",
}

# Common generation options - TypedDict for clean JSON mapping
COMMON_OPTIONS = [
    "--input-file-type",
    "jsonschema",
    "--output-model-type",
    "typing.TypedDict",
    "--use-standard-collections",
    "--use-union-operator",
    "--target-python-version",
    "3.11",
    "--collapse-root-models",
    "--use-double-quotes",
]

HEADER = '''"""Auto-generated TypedDict classes from JSON schema.

DO NOT EDIT THIS FILE MANUALLY.
Generated by: python generate_dtos.py

To regenerate, run from the repository root:
    python generate_dtos.py
"""

'''


def check_datamodel_codegen() -> bool:
    """Check if datamodel-code-generator is installed."""
    try:
        result = subprocess.run(  # noqa: S603
            ["datamodel-codegen", "--version"],  # noqa: S607
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode == 0:
            print(f"Found datamodel-code-generator: {result.stdout.strip()}")
            return True
    except FileNotFoundError:
        pass

    print("Error: datamodel-code-generator is not installed.")
    print("Install it with: pip install datamodel-code-generator")
    return False


def generate_dto(schema_file: Path, output_file: Path) -> bool:
    """Generate Python dataclasses from a JSON schema file."""
    print(f"\nGenerating: {schema_file.name} -> {output_file.relative_to(SCRIPT_DIR)}")

    # Ensure output directory exists
    output_file.parent.mkdir(parents=True, exist_ok=True)

    # Build command
    cmd = [
        "datamodel-codegen",
        "--input",
        str(schema_file),
        "--output",
        str(output_file),
        *COMMON_OPTIONS,
    ]

    # Run generator
    result = subprocess.run(cmd, capture_output=True, text=True, check=False)  # noqa: S603

    if result.returncode != 0:
        print(f"Error generating {output_file.name}:")
        print(result.stderr)
        return False

    # Add header to generated file
    content = output_file.read_text()

    # Remove any existing "generated by" comments and add our header
    lines = content.split("\n")
    # Skip initial comments that datamodel-codegen adds
    start_idx = 0
    for i, line in enumerate(lines):
        if not line.startswith("#") and line.strip():
            start_idx = i
            break

    new_content = HEADER + "\n".join(lines[start_idx:])

    # Remove 'closed=True' from TypedDict - not supported by mypy yet
    new_content = new_content.replace(", closed=True", "")

    # Remove duplicate TypedDict import from typing_extensions
    new_content = new_content.replace("from typing_extensions import TypedDict\n\n", "")

    output_file.write_text(new_content)

    print(f"  ✓ Generated {output_file.name}")
    return True


def main() -> int:
    """Main entry point."""
    print("=" * 60)
    print("Vista SDK - JSON Schema to Python DTO Generator")
    print("=" * 60)

    # Check dependencies
    if not check_datamodel_codegen():
        return 1

    # Verify schema directory exists
    if not SCHEMA_DIR.exists():
        print(f"Error: Schema directory not found: {SCHEMA_DIR}")
        return 1

    # Generate each schema
    success = True
    for schema_name, output_path in SCHEMAS.items():
        schema_file = SCHEMA_DIR / schema_name
        output_file = OUTPUT_DIR / output_path

        if not schema_file.exists():
            print(f"Warning: Schema file not found: {schema_file}")
            continue

        if not generate_dto(schema_file, output_file):
            success = False

    print("\n" + "=" * 60)
    if success:
        print("✓ All DTOs generated successfully!")
        print("\nGenerated files:")
        for output_path in SCHEMAS.values():
            print(f"  - python/src/vista_sdk/system_text_json/{output_path}")
    else:
        print("✗ Some DTOs failed to generate. See errors above.")
    print("=" * 60)

    return 0 if success else 1


if __name__ == "__main__":
    sys.exit(main())
