[project]
name = "vista_sdk"
version = "0.0.1"
requires-python = ">=3.8"

[project.urls]
Homepage = "https://github.com/vista-sdk"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
