"""Auto-generated TypedDict classes from JSON schema.

DO NOT EDIT THIS FILE MANUALLY.
Generated by: python generate_dtos.py

To regenerate, run from the repository root:
    python generate_dtos.py
"""

from __future__ import annotations

from typing import Literal, NotRequired, TypedDict


class VersionInformation(TypedDict):
    NamingRule: str
    NamingSchemeVersion: str
    ReferenceURL: NotRequired[str]


class NameObject(TypedDict):
    NamingRule: str


class DataChannelType(TypedDict):
    Type: str
    UpdateCycle: NotRequired[float]
    CalculationPeriod: NotRequired[float]


class Range(TypedDict):
    High: float
    Low: float


class Unit(TypedDict):
    UnitSymbol: str
    QuantityName: NotRequired[str]


class Restriction(TypedDict):
    Enumeration: NotRequired[list[str]]
    FractionDigits: NotRequired[int]
    Length: NotRequired[int]
    MaxExclusive: NotRequired[float]
    MaxInclusive: NotRequired[float]
    MaxLength: NotRequired[int]
    MinExclusive: NotRequired[float]
    MinInclusive: NotRequired[float]
    MinLength: NotRequired[int]
    Pattern: NotRequired[str]
    TotalDigits: NotRequired[int]
    WhiteSpace: NotRequired[Literal["Preserve", "Replace", "Collapse"]]


class ConfigurationReference(TypedDict):
    ID: str
    Version: NotRequired[str]
    TimeStamp: str


class Header(TypedDict):
    ShipID: str
    DataChannelListID: ConfigurationReference
    VersionInformation: NotRequired[VersionInformation]
    Author: NotRequired[str]
    DateCreated: NotRequired[str]


class DataChannelID(TypedDict):
    LocalID: str
    ShortID: NotRequired[str]
    NameObject: NotRequired[NameObject]


class Format(TypedDict):
    Type: str
    Restriction: NotRequired[Restriction]


class Property(TypedDict):
    DataChannelType: DataChannelType
    Format: Format
    Range: NotRequired[Range]
    Unit: NotRequired[Unit]
    QualityCoding: NotRequired[str]
    AlertPriority: NotRequired[str]
    Name: NotRequired[str]
    Remarks: NotRequired[str]


class DataChannel(TypedDict):
    DataChannelID: DataChannelID
    Property: Property


class DataChannelList(TypedDict):
    DataChannel: list[DataChannel]


class Package(TypedDict):
    Header: Header
    DataChannelList: DataChannelList


class DataChannelListPackage(TypedDict):
    Package: Package
