name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '6.0.x'

jobs:
  build:
    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore tools
        run: |
          cd csharp
          dotnet tool restore

      - name: Check formatting
        run: |
          cd csharp
          dotnet csharpier --check   

      - name: Install dependencies
        run:  dotnet restore

      - name: Build
        run: dotnet build --configuration Release  --no-restore
      # TO DO: Create test.sh
      - name: Test
        run: dotnet test --no-build --verbosity normal
