name: Node.js Package

on:
  workflow_dispatch:
    branches: [main, feature/js-sdk, feature/js-yaml-build-and-publish]
  push:
    branches: [main, feature/js-sdk, feature/js-yaml-build-and-publish]
  pull_request:
    branches: [main, feature/js-sdk, feature/js-yaml-build-and-publish]
env:
  CI_BUILD: true

jobs:
  publish-npm:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/          
      - run: cd js/src/vista-sdk; npm ci; npm run build;
      - if: ${{ success() && !github.base_ref }}
        run: cd js/src/vista-sdk; npm version $(node -p "require('./package.json').version")-${{ github.run_id }}; npm publish --access public;
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}