name: Node.js Package

on:
  workflow_dispatch:
    branches: [main, feature/js-sdk, feature/js-yaml-build-and-publish]
  push:
    branches: [main, feature/js-sdk, feature/js-yaml-build-and-publish]
  pull_request:
    branches: [main, feature/js-sdk, feature/js-yaml-build-and-publish]
env:
  CI_BUILD: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      # - run: node js/src/vista-sdk/source-generator/dirtest.js
      - run: cd js/src/vista-sdk; npm ci; npm run build;
#      - run: cd js/src/vista-sdk; npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/          
      - run: cd js/src/vista-sdk; npm ci; npm run build; export VERSION=$(node -p "require('./package.json').version")      
#      - run: cd js/src/vista-sdk; npm test
      - if: ${{ success() && !github.base_ref }}
        run: cd js/src/vista-sdk; npm version ${{VERSION}}-${{ github.run_id }}; npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}